#user  nobody;
worker_processes  1;

events {
    worker_connections  1024;
}
http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;


    upstream  hiss-app {
        server localhost:18081;
    }

    server {
        listen 3000;
        location / {
            root /usr/share/nginx/html/hiss-center/;
            index index.html;
        }

        location ~/api/(.*) {
            proxy_pass http://hiss-app/$1;
            proxy_set_header HOST $host;  # 不改变源请求头的值
            proxy_pass_request_body on;  #开启获取请求体
            proxy_pass_request_headers on;  #开启获取请求头
            proxy_set_header X-Real-IP $remote_addr;   # 记录真实发出请求的客户端IP
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  #记录代理信息
        }

        location /v1/receiver {
            proxy_pass http://hiss-app/v1/receiver;
            proxy_set_header HOST $host;  # 不改变源请求头的值
            proxy_pass_request_body on;  #开启获取请求体
            proxy_pass_request_headers on;  #开启获取请求头
            proxy_set_header X-Real-IP $remote_addr;   # 记录真实发出请求的客户端IP
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  #记录代理信息
        }
    }

    upstream  zhyl-app {
        server localhost:9995;
    }

    server {
        listen 3001;
        location / {
                root /usr/share/nginx/html/project-zhyl-admin-vue3-java/;
                index index.html;
        }

        location ~/api/v1/receiver/(.*) {
            proxy_pass http://hiss-app/v1/receiver/$1;
            proxy_set_header HOST $host;  # 不改变源请求头的值
            proxy_pass_request_body on;  #开启获取请求体
            proxy_pass_request_headers on;  #开启获取请求头
            proxy_set_header X-Real-IP $remote_addr;   # 记录真实发出请求的客户端IP
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  #记录代理信息
        }

        location /v1/receiver {
            proxy_pass http://hiss-app/v1/receiver;
            proxy_set_header HOST $host;  # 不改变源请求头的值
            proxy_pass_request_body on;  #开启获取请求体
            proxy_pass_request_headers on;  #开启获取请求头
            proxy_set_header X-Real-IP $remote_addr;   # 记录真实发出请求的客户端IP
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  #记录代理信息
        }

        location ~/api/(.*) {
            proxy_pass http://zhyl-app/$1;
            proxy_set_header HOST $host;  # 不改变源请求头的值
            proxy_pass_request_body on;  #开启获取请求体
            proxy_pass_request_headers on;  #开启获取请求头
            proxy_set_header X-Real-IP $remote_addr;   # 记录真实发出请求的客户端IP
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  #记录代理信息
        }
    }

    server {
            listen 3002;
            location / {
                    root /usr/share/nginx/html/ppt/;
                    index index.html;
            }
    }
}
